CREATE TABLE t_watchlist_item (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    user_id BIGINT NOT NULL COMMENT '用户ID',
    anime_id BIGINT NOT NULL COMMENT '番剧ID',
    status VARCHAR(20) NOT NULL COMMENT '追番状态：WANT_TO_WATCH/WATCHING/WATCHED/DROPPED',
    current_episode INT NOT NULL DEFAULT 0 COMMENT '当前观看进度',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_anime (user_id, anime_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户追番记录表';
